# Generated by Django 2.0.2 on 2019-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='fecha'),
        ),
    ]
