# Generated by Django 2.0.2 on 2019-02-11 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_auto_20190211_0841'),
        ('torneos', '0002_torneo_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='torneo',
            name='equipos',
            field=models.ManyToManyField(related_name='equipos', to='equipos.Equipo', verbose_name='Equipos'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='descripcion',
            field=models.TextField(max_length=200, verbose_name='Descripcion'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='fecha',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='participantes',
            field=models.IntegerField(null=True, verbose_name='Participantes'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Titulo'),
        ),
        migrations.AlterField(
            model_name='torneo',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Actualizado'),
        ),
    ]
