# Generated by Django 2.0.2 on 2019-02-12 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_participaciones'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participaciones',
            old_name='posicion',
            new_name='puesto',
        ),
    ]
