# Generated by Django 2.0.2 on 2019-02-04 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fundacion', models.IntegerField(default=1)),
                ('presidente', models.CharField(default='a', max_length=100)),
                ('direccion', models.CharField(default='a', max_length=100)),
                ('web', models.CharField(default='a', max_length=100)),
                ('estadio', models.CharField(default='a', max_length=100)),
                ('puntos', models.IntegerField()),
                ('imagen', models.ImageField(upload_to='equipos')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Equipo',
                'verbose_name_plural': 'Equipos',
                'ordering': ['-puntos'],
            },
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('imagen', models.ImageField(upload_to='equipos')),
                ('edad', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('pais', models.CharField(max_length=100)),
                ('posicion', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='equipos.Equipo', verbose_name='Equipo')),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['-goles'],
            },
        ),
    ]
