# Generated by Django 2.0.2 on 2019-02-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0002_auto_20190209_1940'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugador',
            name='altura',
            field=models.IntegerField(verbose_name='Estatura'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='edad',
            field=models.IntegerField(verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='goles',
            field=models.IntegerField(verbose_name='Goles'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='imagen',
            field=models.ImageField(upload_to='equipos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='pais',
            field=models.CharField(max_length=100, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='jugador',
            name='posicion',
            field=models.CharField(max_length=100, verbose_name='Posición'),
        ),
    ]
