# Generated by Django 2.0.2 on 2019-02-11 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('equipos', '0003_auto_20190209_1941'),
    ]

    operations = [
        migrations.CreateModel(
            name='JugadorPerfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('imagen', models.ImageField(upload_to='equipos', verbose_name='Foto')),
                ('edad', models.IntegerField(verbose_name='Edad')),
                ('goles', models.IntegerField(verbose_name='Goles')),
                ('pais', models.CharField(max_length=100, verbose_name='País')),
                ('posicion', models.CharField(max_length=100, verbose_name='Posición')),
                ('altura', models.IntegerField(verbose_name='Estatura')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Actualizado')),
                ('equipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='jugadores', to='equipos.Equipo', verbose_name='Equipo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
                'ordering': ['-goles'],
            },
        ),
        migrations.RemoveField(
            model_name='jugador',
            name='equipo',
        ),
        migrations.DeleteModel(
            name='Jugador',
        ),
    ]
