# Generated by Django 2.0.2 on 2019-02-11 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0004_auto_20190211_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadorperfil',
            name='altura',
            field=models.IntegerField(blank=True, null=True, verbose_name='Estatura'),
        ),
        migrations.AlterField(
            model_name='jugadorperfil',
            name='edad',
            field=models.IntegerField(blank=True, null=True, verbose_name='Edad'),
        ),
        migrations.AlterField(
            model_name='jugadorperfil',
            name='goles',
            field=models.IntegerField(blank=True, null=True, verbose_name='Goles'),
        ),
        migrations.AlterField(
            model_name='jugadorperfil',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='equipos', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='jugadorperfil',
            name='nombre',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='jugadorperfil',
            name='pais',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='País'),
        ),
        migrations.AlterField(
            model_name='jugadorperfil',
            name='posicion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Posición'),
        ),
    ]
