# Generated by Django 2.0.2 on 2019-02-12 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0006_jugadorperfil_capitan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipo',
            options={'ordering': ['nombre'], 'verbose_name': 'Equipo', 'verbose_name_plural': 'Equipos'},
        ),
        migrations.RemoveField(
            model_name='equipo',
            name='puntos',
        ),
    ]
