# Generated by Django 2.0.2 on 2019-02-15 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0008_auto_20190212_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadorperfil',
            name='equipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jugadores', to='equipos.Equipo', verbose_name='Equipo'),
        ),
    ]
